function sftApplyTheme(ax, theme)
%SFTAPPLYTHEME Apply shared styling to an axes object.

if nargin < 1 || isempty(ax)
    ax = gca;
end
if nargin < 2 || isempty(theme)
    theme = sftTheme();
end

set(ax, ...
    'FontName', theme.FontName, ...
    'FontSize', theme.FontSize, ...
    'LineWidth', theme.LineWidth, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'XColor', theme.AxisColor, ...
    'YColor', theme.AxisColor, ...
    'GridColor', theme.GridColor, ...
    'Layer', 'top');

textHandles = [ax.Title, ax.XLabel, ax.YLabel, ax.ZLabel];
set(textHandles, 'FontName', theme.FontName, 'Color', theme.AxisColor);
set(ax.Title, 'FontSize', theme.FontSize + 2, 'FontWeight', 'bold');
set([ax.XLabel, ax.YLabel, ax.ZLabel], 'FontSize', theme.FontSize + 1);
end
