function templates = sftTemplateRegistry()
%SFTTEMPLATEREGISTRY Return metadata for every public gallery template.

ensureExamplesOnPath();

templates = [
    makeTemplate("line_plot", @renderLinePlot, "Show time trend", ["trend", "line"], "line")
    makeTemplate("confidence_interval", @renderConfidenceInterval, ...
        "Show uncertainty", ["uncertainty", "line"], "confidence")
    makeTemplate("uncertainty_fan_chart", @renderUncertaintyFanChart, ...
        "Show widening forecast uncertainty", ["uncertainty", "forecast"], "uncertainty_fan_chart")
    makeTemplate("scatter_plot", @renderScatterPlot, ...
        "Show grouped x-y relationship", ["scatter", "groups"], "scatter")
    makeTemplate("ternary_scatter", @renderTernaryScatter, ...
        "Show three-part compositions", ["composition", "scatter"], "ternary_scatter")
    makeTemplate("density_scatter", @renderDensityScatter, ...
        "Show dense x-y relationship", ["scatter", "density"], "density_scatter")
    makeTemplate("contour_scatter", @renderContourScatter, ...
        "Show local density structure", ["scatter", "density", "contour"], "contour_scatter")
    makeTemplate("bland_altman_plot", @renderBlandAltmanPlot, ...
        "Check agreement between two methods", ["agreement", "comparison"], "bland_altman_plot")
    makeTemplate("grouped_bar", @renderGroupedBar, ...
        "Compare grouped values", ["bar", "comparison"], "grouped_bar")
    makeTemplate("grouped_error_bar", @renderGroupedErrorBar, ...
        "Compare grouped values with uncertainty", ["bar", "uncertainty"], "grouped_error_bar")
    makeTemplate("forest_plot", @renderForestPlot, ...
        "Compare estimates with intervals", ["interval", "comparison"], "forest_plot")
    makeTemplate("waterfall_chart", @renderWaterfallChart, ...
        "Show cumulative contribution steps", ["waterfall", "change"], "waterfall_chart")
    makeTemplate("butterfly_comparison", @renderButterflyComparison, ...
        "Compare two sides around a baseline", ["bar", "comparison"], "butterfly")
    makeTemplate("paired_slopegraph", @renderPairedSlopegraph, ...
        "Compare paired before-after values", ["comparison", "paired"], "paired_slopegraph")
    makeTemplate("waffle_chart", @renderWaffleChart, ...
        "Show countable composition", ["composition", "percentage"], "waffle")
    makeTemplate("sankey_flow", @renderSankeyFlow, ...
        "Show flow magnitude across stages", ["flow", "composition"], "sankey_flow")
    makeTemplate("positive_negative_area", @renderPositiveNegativeArea, ...
        "Show signed change around a baseline", ["area", "change"], "positive_negative_area")
    makeTemplate("ridgeline_plot", @renderRidgelinePlot, ...
        "Compare many distributions", ["distribution", "density"], "ridgeline")
    makeTemplate("radar_chart", @renderRadarChart, ...
        "Compare normalized metric profiles", ["profile", "metrics"], "radar")
    makeTemplate("parallel_coordinates", @renderParallelCoordinates, ...
        "Compare multivariate sample profiles", ["multivariate", "profile"], "parallel_coordinates")
    makeTemplate("heatmap", @renderHeatmap, ...
        "Show matrix values", ["matrix", "heatmap"], "heatmap")
    makeTemplate("correlation_bubble", @renderCorrelationBubble, ...
        "Show correlation strength and sign", ["matrix", "correlation"], "correlation_bubble")
    makeTemplate("double_triangle_heatmap", @renderDoubleTriangleHeatmap, ...
        "Compare two pairwise matrices", ["matrix", "comparison"], "double_triangle_heatmap")
    makeTemplate("zoomed_inset_line", @renderZoomedInsetLine, ...
        "Show a long trend and local event", ["trend", "inset"], "zoomed_inset_line")
    makeTemplate("stacked_time_series", @renderStackedTimeSeries, ...
        "Compare synchronized signals on one time axis", ["trend", "time"], "stacked_time_series")
    makeTemplate("calendar_heatmap", @renderCalendarHeatmap, ...
        "Show daily values over weeks", ["time", "heatmap"], "calendar_heatmap")
    makeTemplate("bubble_matrix", @renderBubbleMatrix, ...
        "Show matrix magnitude with bubble area", ["matrix", "bubble"], "bubble_matrix")
    makeTemplate("box_jitter", @renderBoxJitter, ...
        "Compare distributions and observations", ["distribution", "points"], "box_jitter")
    makeTemplate("lollipop_ranking", @renderLollipopRanking, ...
        "Rank factors or features", ["ranking", "lollipop"], "lollipop")
    makeTemplate("multi_panel_overview", @renderMultiPanelOverview, ...
        "Combine small plots in one figure", ["layout", "multipanel"], "line+scatter+grouped_bar+lollipop")
    makeTemplate("surface_3d", @renderSurface3D, ...
        "Show a smooth 3D response", ["surface", "3d"], "surface")
];
end

function template = makeTemplate(name, renderer, task, tags, dataKind)
template = struct( ...
    'Name', name, ...
    'Renderer', renderer, ...
    'OutputName', name, ...
    'Task', task, ...
    'Tags', tags, ...
    'SyntheticDataKind', dataKind);
end

function ensureExamplesOnPath()
srcDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(srcDir);
examplesDir = fullfile(projectRoot, 'examples');
if exist(examplesDir, 'dir')
    addpath(examplesDir);
end
end
