function templates = sftTemplateRegistry()
%SFTTEMPLATEREGISTRY Return metadata for every public gallery template.

ensureExamplesOnPath();

templates = [
    makeTemplate("line_plot", @renderLinePlot, "Show time trend", ["trend", "line"])
    makeTemplate("confidence_interval", @renderConfidenceInterval, ...
        "Show uncertainty", ["uncertainty", "line"])
    makeTemplate("uncertainty_fan_chart", @renderUncertaintyFanChart, ...
        "Show widening forecast uncertainty", ["uncertainty", "forecast"])
    makeTemplate("scatter_plot", @renderScatterPlot, ...
        "Show grouped x-y relationship", ["scatter", "groups"])
    makeTemplate("density_scatter", @renderDensityScatter, ...
        "Show dense x-y relationship", ["scatter", "density"])
    makeTemplate("contour_scatter", @renderContourScatter, ...
        "Show local density structure", ["scatter", "density", "contour"])
    makeTemplate("grouped_bar", @renderGroupedBar, ...
        "Compare grouped values", ["bar", "comparison"])
    makeTemplate("grouped_error_bar", @renderGroupedErrorBar, ...
        "Compare grouped values with uncertainty", ["bar", "uncertainty"])
    makeTemplate("butterfly_comparison", @renderButterflyComparison, ...
        "Compare two sides around a baseline", ["bar", "comparison"])
    makeTemplate("paired_slopegraph", @renderPairedSlopegraph, ...
        "Compare paired before-after values", ["comparison", "paired"])
    makeTemplate("waffle_chart", @renderWaffleChart, ...
        "Show countable composition", ["composition", "percentage"])
    makeTemplate("sankey_flow", @renderSankeyFlow, ...
        "Show flow magnitude across stages", ["flow", "composition"])
    makeTemplate("positive_negative_area", @renderPositiveNegativeArea, ...
        "Show signed change around a baseline", ["area", "change"])
    makeTemplate("ridgeline_plot", @renderRidgelinePlot, ...
        "Compare many distributions", ["distribution", "density"])
    makeTemplate("radar_chart", @renderRadarChart, ...
        "Compare normalized metric profiles", ["profile", "metrics"])
    makeTemplate("parallel_coordinates", @renderParallelCoordinates, ...
        "Compare multivariate sample profiles", ["multivariate", "profile"])
    makeTemplate("heatmap", @renderHeatmap, ...
        "Show matrix values", ["matrix", "heatmap"])
    makeTemplate("correlation_bubble", @renderCorrelationBubble, ...
        "Show correlation strength and sign", ["matrix", "correlation"])
    makeTemplate("double_triangle_heatmap", @renderDoubleTriangleHeatmap, ...
        "Compare two pairwise matrices", ["matrix", "comparison"])
    makeTemplate("zoomed_inset_line", @renderZoomedInsetLine, ...
        "Show a long trend and local event", ["trend", "inset"])
    makeTemplate("calendar_heatmap", @renderCalendarHeatmap, ...
        "Show daily values over weeks", ["time", "heatmap"])
    makeTemplate("bubble_matrix", @renderBubbleMatrix, ...
        "Show matrix magnitude with bubble area", ["matrix", "bubble"])
    makeTemplate("box_jitter", @renderBoxJitter, ...
        "Compare distributions and observations", ["distribution", "points"])
    makeTemplate("lollipop_ranking", @renderLollipopRanking, ...
        "Rank factors or features", ["ranking", "lollipop"])
    makeTemplate("multi_panel_overview", @renderMultiPanelOverview, ...
        "Combine small plots in one figure", ["layout", "multipanel"])
    makeTemplate("surface_3d", @renderSurface3D, ...
        "Show a smooth 3D response", ["surface", "3d"])
];
end

function template = makeTemplate(name, renderer, task, tags)
template = struct( ...
    'Name', name, ...
    'Renderer', renderer, ...
    'OutputName', name, ...
    'Task', task, ...
    'Tags', tags);
end

function ensureExamplesOnPath()
srcDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(srcDir);
examplesDir = fullfile(projectRoot, 'examples');
if exist(examplesDir, 'dir')
    addpath(examplesDir);
end
end
